# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='day1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day1', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u043f\u0435\u0440\u0448\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day1', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441 \u043f\u0435\u0440\u0448\u043e\u0433\u043e \u0434\u043d\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='day2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day2', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u0434\u0440\u0443\u0433\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day2', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441 \u0434\u0440\u0443\u0433\u043e\u0433\u043e \u0434\u043d\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='day3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day3', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u0442\u0440\u0435\u0442\u044c\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day3', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441 \u0442\u0440\u0435\u0442\u044c\u043e\u0433\u043e \u0434\u043d\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='day4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day4', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u0447\u0435\u0442\u0432\u0435\u0440\u0442\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day4', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441 \u0447\u0435\u0442\u0432\u0435\u0440\u0442\u043e\u0433\u043e \u0434\u043d\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='day5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day5', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u043f*\u044f\u0442\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day5', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441 \u043f*\u044f\u0442\u043e\u0433\u043e \u0434\u043d\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u043c\u0430\u043d\u0434\u0440\u0456\u0432\u043a\u0438')),
                ('describe', models.TextField(blank=True, verbose_name='\u043a\u043e\u0440\u043e\u0442\u043a\u0438\u0439 \u043e\u043f\u0438\u0441')),
                ('cities', models.CharField(max_length=256, verbose_name='\u043c\u0456\u0441\u0442\u0430')),
                ('price', models.CharField(blank=True, default='', max_length=256, verbose_name='\u0446\u0456\u043d\u0430')),
                ('start_date', models.DateField(null=True, verbose_name='\u043f\u043e\u0447\u0430\u0442\u043e\u043a \u043c\u0430\u043d\u0434\u0440\u0456\u0432\u043a\u0438')),
                ('end_date', models.DateField(null=True, verbose_name='\u043a\u0456\u043d\u0435\u0446\u044c \u043c\u0430\u043d\u0434\u0440\u0456\u0432\u043a\u0438')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0444\u043e\u0442\u043e')),
                ('roadmap', models.TextField(blank=True, verbose_name='\u043c\u0430\u0440\u0448\u0440\u0443\u0442')),
                ('conditions', models.TextField(blank=True, verbose_name='\u0443\u043c\u043e\u0432\u0438')),
                ('documents', models.TextField(blank=True, verbose_name='\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0438')),
                ('options', models.TextField(blank=True, verbose_name='\u0434\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043e\u043f\u0446\u0456\u0457')),
                ('day_1', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='vohni.day1', verbose_name='\u043e\u043f\u0438\u0441 \u043f\u0435\u0440\u0448\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day_2', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='vohni.day2', verbose_name='\u043e\u043f\u0438\u0441 \u0434\u0440\u0443\u0433\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day_3', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='vohni.day3', verbose_name='\u043e\u043f\u0438\u0441 \u0442\u0440\u0435\u0442\u044c\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day_4', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='vohni.day4', verbose_name='\u043e\u043f\u0438\u0441 \u0447\u0435\u0442\u0432\u0435\u0440\u0442\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day_5', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='vohni.day5', verbose_name='\u043e\u043f\u0438\u0441 \u043f*\u044f\u0442\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='photologue.Gallery', verbose_name='\u0444\u043e\u0442\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u043d\u0434\u0440\u0456\u0432\u043a\u0430',
                'verbose_name_plural': '\u041c\u0430\u043d\u0434\u0440\u0456\u0432\u043a\u0438',
            },
        ),
    ]
