# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vohni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='day_1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vohni.day1', verbose_name='\u043e\u043f\u0438\u0441 \u043f\u0435\u0440\u0448\u043e\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='day_2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vohni.day2', verbose_name='\u043e\u043f\u0438\u0441 \u0434\u0440\u0443\u0433\u043e\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='day_3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vohni.day3', verbose_name='\u043e\u043f\u0438\u0441 \u0442\u0440\u0435\u0442\u044c\u043e\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='day_4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vohni.day4', verbose_name='\u043e\u043f\u0438\u0441 \u0447\u0435\u0442\u0432\u0435\u0440\u0442\u043e\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='day_5',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vohni.day5', verbose_name='\u043e\u043f\u0438\u0441 \u043f*\u044f\u0442\u043e\u0433\u043e \u0434\u043d\u044f'),
        ),
    ]
