# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vohni', '0002_auto_20160311_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='day6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day6', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u0448\u043e\u0441\u0442\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day6', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441 \u0448\u043e\u0441\u0442\u043e\u0433\u043e \u0434\u043d\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='day7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day7', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u0441\u044c\u043e\u043c\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day7', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441 \u0441\u044c\u043e\u043c\u043e\u0433\u043e \u0434\u043d\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='day8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day8', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u0432\u043e\u0441\u044c\u043c\u043e\u0433\u043e \u0434\u043d\u044f')),
                ('day8', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441 \u0432\u043e\u0441\u044c\u043c\u043e\u0433\u043e \u0434\u043d\u044f')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='donation',
            field=models.TextField(blank=True, null=True, verbose_name='\u043f\u043e\u0436\u0435\u0440\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='journey',
            name='price_include',
            field=models.TextField(blank=True, null=True, verbose_name='\u0443 \u0432\u0430\u0440\u0442\u0456\u0441\u0442\u044c \u0432\u0445\u043e\u0434\u0438\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='journey',
            name='price_not_include',
            field=models.TextField(blank=True, null=True, verbose_name='\u0443 \u0432\u0430\u0440\u0442\u0456\u0441\u0442\u044c \u043d\u0435 \u0432\u0445\u043e\u0434\u0438\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='options',
            field=models.TextField(blank=True, null=True, verbose_name='\u0434\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043e\u043f\u0446\u0456\u0457'),
        ),
        migrations.AddField(
            model_name='journey',
            name='day_6',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vohni.day6', verbose_name='\u043e\u043f\u0438\u0441 \u0448\u043e\u0441\u0442\u043e\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='journey',
            name='day_7',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vohni.day7', verbose_name='\u043e\u043f\u0438\u0441 \u0441\u044c\u043e\u043c\u043e\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='journey',
            name='day_8',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vohni.day8', verbose_name='\u043e\u043f\u0438\u0441 \u0432\u043e\u0441\u044c\u043c\u043e\u0433\u043e \u0434\u043d\u044f'),
        ),
    ]
