# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vohni', '0004_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_email',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='\u0435\u043c\u0435\u0439\u043b\u0438 \u043a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0456\u0432'),
        ),
    ]
