# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vohni', '0006_auto_20160321_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_email',
            name='name',
        ),
    ]
