# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vohni', '0009_user_email_journey_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_email',
            name='journey_choice',
        ),
    ]
