# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vohni', '0010_remove_user_email_journey_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_email',
            name='journey_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vohni.Journey', verbose_name='\u041c\u0430\u043d\u0434\u0440\u0456\u0432\u043a\u0430'),
        ),
    ]
