# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u043d\u0430\u0437\u0432\u0430 \u043f\u043e\u0441\u0442\u0430')),
                ('datetime', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0456\u0457')),
                ('text', models.TextField(blank=True, verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('blog_photo', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0444\u043e\u0442\u043e')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0441\u0442',
                'verbose_name_plural': '\u041f\u043e\u0441\u0442\u0438',
            },
        ),
    ]
